# Example configuration for using an external database
# Copy this file and modify it for your external database setup

# Global settings
namespace: browser-sandbox
environment: production

# Database configuration - Using external database
database:
  type: external
  externalUrl: "postgres://myuser:mypassword@my-external-db.example.com:5432/mydatabase?sslmode=require"

# API configuration
api:
  image:
    repository: ghcr.io/browsersec/kubebrowse
    tag: sha-09dfa1f
    pullPolicy: IfNotPresent
  replicas: 2
  resources:
    requests:
      memory: "128Mi"
      cpu: "200m"
    limits:
      memory: "256Mi"
      cpu: "400m"
  service:
    type: LoadBalancer
    port: 4567

# Frontend configuration
frontend:
  image:
    repository: ghcr.io/browsersec/kubebrowse-frontend
    tag: chore-improve-back
    pullPolicy: IfNotPresent
  replicas: 3
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"
  service:
    type: LoadBalancer
    port: 80

# Redis configuration
redis:
  image:
    repository: redis
    tag: alpine
  replicas: 1
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"

# Guacamole daemon configuration
guacd:
  image:
    repository: guacamole/guacd
    tag: latest
  replicas: 2
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"

# MinIO configuration
minio:
  image:
    repository: minio/minio
    tag: latest
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "300m"
  storage: 20Gi
  credentials:
    accessKey: minioaccesskey
    secretKey: miniosecretkey
    bucket: browser-sandbox

# Session configuration
sessionTimeouts:
  podSessionTimeout: 15
  podSessionTTL: 10

# OAuth configuration
oauth:
  github:
    clientId: "your-production-client-id"
    clientSecret: "your-production-client-secret"
    callbackUrl: "https://yourdomain.com/auth/oauth/github/callback"

# SMTP configuration
smtp:
  host: "smtp.yourprovider.com"
  port: "587"
  username: "your-smtp-user"
  password: "your-smtp-password"
  fromEmail: "noreply@yourdomain.com"

# Tracing configuration  
tracing:
  jaegerEndpoint: "http://jaeger.yournamespace.svc.cluster.local:14268/api/traces"
  serviceName: "browser-sandbox"
  enabled: true

# Session secret
sessionSecret: "your-production-session-secret"

# Frontend URL
frontendUrl: "https://yourdomain.com"

# Note: When using external database, PostgreSQL-related values are ignored
# as the internal PostgreSQL StatefulSet will not be deployed