apiVersion: apps/v1
kind: Deployment
metadata:
  name: browser-sandbox-api
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app: browser-sandbox-api
  template:
    metadata:
      labels:
        app: browser-sandbox-api
    spec:
      serviceAccountName: browser-sandbox-sa
      containers:
        - name: api
          image: {{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          ports:
            - containerPort: 4567
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
          env:
            - name: GUACD_ADDRESS
              value: "guacd.{{ .Values.namespace }}.svc.cluster.local:4822"
            - name: DATABASE_URL
              value: "postgres://{{ .Values.postgres.credentials.username }}:{{ .Values.postgres.credentials.password }}@postgres.{{ .Values.namespace }}.svc.cluster.local:5432/{{ .Values.postgres.credentials.database }}?sslmode=disable"
            - name: POSTGRES_HOST
              value: "postgres"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
            - name: POSTGRES_DB
              value: {{ .Values.postgres.credentials.database | quote }}
            - name: REDIS_HOST
              value: "redis.{{ .Values.namespace }}.svc.cluster.local"
            - name: REDIS_PORT
              value: "6379"
            - name: MINIO_ENDPOINT
              value: "minio:9000"
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: access-key
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: secret-key
            - name: MINIO_BUCKET
              value: {{ .Values.minio.credentials.bucket | quote }}
            - name: CLAMAV_ADDRESS
              value: "http://clamd-api.{{ .Values.namespace }}.svc.cluster.local:3000"
            - name: KUBERNETES_NAMESPACE
              value: {{ .Values.namespace | quote }}
            - name: POD_SESSION_TIMEOUT
              value: {{ .Values.sessionTimeouts.podSessionTimeout | quote }}
            - name: POD_SESSION_TTL
              value: {{ .Values.sessionTimeouts.podSessionTTL | quote }}
            - name: JAEGER_ENDPOINT
              value: {{ .Values.tracing.jaegerEndpoint | quote }}
            - name: JAEGER_SERVICE_NAME
              value: {{ .Values.tracing.serviceName | quote }}
            - name: DISTRIBUTED_TRACING
              value: {{ .Values.tracing.enabled | quote }}
            - name: GITHUB_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: github-oauth
                  key: client-id
            - name: GITHUB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: github-oauth
                  key: client-secret
            - name: GITHUB_CALLBACK_URL
              value: {{ .Values.oauth.github.callbackUrl | quote }}
            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: session-secret
                  key: secret
            - name: FRONTEND_URL
              value: {{ .Values.frontendUrl | quote }}
            - name: ENVIRONMENT
              value: {{ .Values.environment | quote }}
            - name: SMTP_HOST
              value: {{ .Values.smtp.host | quote }}
            - name: SMTP_PORT
              value: {{ .Values.smtp.port | quote }}
            - name: SMTP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: smtp-credentials
                  key: username
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: smtp-credentials
                  key: password
            - name: FROM_EMAIL
              value: {{ .Values.smtp.fromEmail | quote }}
          securityContext: {}
---
apiVersion: v1
kind: Service
metadata:
  name: browser-sandbox-api
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: 4567
      {{- if and (eq .Values.api.service.type "NodePort") .Values.api.service.nodePort }}
      nodePort: {{ .Values.api.service.nodePort }}
      {{- end }}
  selector:
    app: browser-sandbox-api