apiVersion: apps/v1
kind: Deployment
metadata:
  name: guacd
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.guacd.replicas }}
  selector:
    matchLabels:
      app: guacd
  template:
    metadata:
      labels:
        app: guacd
    spec:
      containers:
        - name: guacd
          image: {{ .Values.guacd.image.repository }}:{{ .Values.guacd.image.tag }}
          ports:
            - containerPort: 4822
          resources:
            {{- toYaml .Values.guacd.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: guacd
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: 4822
      targetPort: 4822
  type: ClusterIP
  selector:
    app: guacd