name: Publish to OCI Registry

on:
  push:
    tags:
      - 'v*'

jobs:
  publish-oci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Package and Push Chart
        run: |
          helm package .
          helm push kubebrowse-*.tgz oci://ghcr.io/browsersec/charts