name: Publish to OCI Registry

on:
  # This workflow is now triggered by the release workflow
  # when a new version is tagged, or manually
  workflow_dispatch:
  push:
    tags:
      - 'v*'

env:
  REGISTRY: ghcr.io
  CHART_NAME: kubebrowse

jobs:
  publish-oci:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: '3.14.0'

      - name: Get Chart Version
        id: chart-version
        run: |
          VERSION=$(helm show chart ./charts/kubebrowse | grep '^version:' | awk '{print $2}')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Chart version: $VERSION"

      - name: Lint Chart
        run: |
          helm lint ./charts/kubebrowse
          echo "✅ Chart linting passed"

      - name: Validate Chart Template
        run: |
          helm template kubebrowse-ci ./charts/kubebrowse --namespace kubebrowse-ci-ns --set namespace=kubebrowse-ci-ns > /dev/null
          echo "✅ Chart template validation passed"

      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin

      - name: Package and Push Chart
        run: |
          helm package ./charts/kubebrowse
          helm push ${{ env.CHART_NAME }}-${{ steps.chart-version.outputs.version }}.tgz oci://${{ env.REGISTRY }}/browsersec/charts
          echo "✅ Chart published to OCI registry"
          echo "📦 Available at: oci://${{ env.REGISTRY }}/browsersec/charts/${{ env.CHART_NAME }}"

      - name: Verify Published Chart
        run: |
          helm pull oci://${{ env.REGISTRY }}/browsersec/charts/${{ env.CHART_NAME }} --version ${{ steps.chart-version.outputs.version }}
          echo "✅ Published chart verification completed"